version: 2
updates:
  - package-ecosystem: "gomod"
    # Disable version updates for gomod dependencies, security updates don't use this configuration
    # See: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
    open-pull-requests-limit: 0
    directory: "../v3"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "security"
      prefix-development: "chore"
      include: "scope"
